apiVersion: v1
kind: Service
metadata:
  name: obp-directory
  labels:
    app: obp-directory
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: obp-directory
    version: v1
---
kind: Service
apiVersion: v1
metadata:
  name: obp-directory
  namespace: forgerock
spec:
  type: ExternalName
  externalName: obp-directory.frdemo.svc.cluster.local
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: obp-directory
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: obp-directory
        version: v1
    spec:
      containers:
      - args:
          - gunicorn
          - -c
          - python:config.gunicorn
          - directory.app:create_app()
        volumeMounts:
          - mountPath: "/app/directory/data"
            name: directory-config
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        name: obp-directory
        image: docker.io/bambebo/obp-directory:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /_status/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /_status/health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 5
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      volumes:
        - name: directory-config
          secret:
            secretName: directory-config

